# Docker Compose Configuration for Rodan-lite
#    +-----+ Production version +-----+ 
# 
# ===========================================
# Summary of the system's services:
# - Frontend: client, nginx
# - Backend: django, iipsrv (for Diva.js)
# - Task Queue: rabbitmq
# - Database: postgres, redis (messaging websocket)
# - Celery: controller (core tasks) | Workers: python3, gpu

volumes:
  rodan-resources:

x-celery-gpu-worker-base: &celery-gpu-worker-base
  command: bash -c "tail -f /dev/null"
  environment:
    TZ: America/Toronto
    SERVER_HOST: localhost
  depends_on:
    - backend-django
    - taskqueue-rabbitmq
    - database-postgres
    - database-redis
    - celery-controller
  env_file:
    - ./scripts/local.env
  volumes:
    - "rodan-resources:/rodan/data"
    - "./backend/django/code:/code/Rodan"
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, compute, utility]

services:
  frontend-nginx:
    container_name: "frontend-nginx"
    build: ./frontend/nginx
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
    ports:
      - "80:80"
      - "443:443"
      - "9002:9002"
    volumes:
      - "rodan-resources:/rodan/data"
    depends_on:
      - backend-iipsrv
      - backend-django
      - frontend-client

  frontend-client:
    container_name: "frontend-client"
    build: ./frontend/client
    volumes:
      - "./frontend/client/code:/code"
      - "./frontend/client/config/configuration.json:/client/configuration.json"

  # Backend service: web server for Django & IIP Server
  backend-django:
    container_name: "backend-django"
    build:
      context: .
      dockerfile: ./backend/django/Dockerfile.bak
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      CELERY_JOB_QUEUE: None
    depends_on:
      - database-postgres
      - taskqueue-rabbitmq
      - database-redis
      - backend-iipsrv
    env_file:
      - ./scripts/local.env
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/django/code:/code/Rodan"

  backend-iipsrv:
    container_name: "backend-iipsrv"
    build: ./backend/iipsrv
    volumes:
      - "rodan-resources:/rodan/data"

  # Celery Controller: 
  # * celery-controller: The main controller for all-things celery
  celery-controller:
    container_name: "celery-controller"
    build:
      context: .
      dockerfile: ./backend/django/Dockerfile.bak
    # command: bash -c "tail -f /dev/null"
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      CELERY_JOB_QUEUE: celery # THIS IS THE IMPORTANT PART
    depends_on:
      - backend-django
      - taskqueue-rabbitmq
      - database-postgres
      - database-redis
    env_file:
      - ./scripts/local.env
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/django/code:/code/Rodan"
  
  
  # Celery Workers: Python and GPU (and more!) 
  # * celery-python-workers
  # * celery-gpu-workers
  # * celery-...

  celery-python-workers:
    container_name: "celery-python-workers"
    build:
      context: .
      dockerfile: ./celery/python-workers/Dockerfile
    command: bash -c "tail -f /dev/null"
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      # CELERY_JOB_QUEUE: Python3
    env_file:
      - ./scripts/local.env
    depends_on:
      - backend-django
      - taskqueue-rabbitmq
      - database-postgres
      - database-redis
      - celery-controller
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/django/code:/code/Rodan"

  celery-gpu-background-removal:
    <<: *celery-gpu-worker-base
    profiles: ["celery-gpu-workers"]
    build:
      context: ./celery/gpu-workers/gpu-background-removal
      dockerfile: ./celery/gpu-workers/gpu-background-removal/Dockerfile
    environment:
      CELERY_JOB_QUEUE: GPU

  celery-gpu-paco-classifier:
    <<: *celery-gpu-worker-base
    profiles: ["celery-gpu-workers"]
    build:
      context: ./celery/gpu-workers/gpu-paco-classifier
      dockerfile: ./celery/gpu-workers/gpu-paco-classifier/Dockerfile
    environment:
      CELERY_JOB_QUEUE: GPU

  celery-gpu-sae-binarization:
    <<: *celery-gpu-worker-base
    profiles: ["celery-gpu-workers"]
    build:
      context: ./celery/gpu-workers/gpu-sae-binarization
      dockerfile: ./celery/gpu-workers/gpu-sae-binarization/Dockerfile
    environment:
      CELERY_JOB_QUEUE: GPU

  celery-gpu-text-alignment:
    <<: *celery-gpu-worker-base
    profiles: ["celery-gpu-workers"]
    build:
      context: ./celery/gpu-workers/gpu-text-alignment
      dockerfile: ./celery/gpu-workers/gpu-text-alignment/Dockerfile
    environment:
      CELERY_JOB_QUEUE: GPU
  # See more: 
  # - https://docs.docker.com/compose/how-tos/gpu-support/
  # - https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html

  # Database: PostgreSQL, Redit (messaging)
  database-postgres:
    container_name: "database-postgres"
    build: ./database/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./scripts/local.env

  database-redis:
    container_name: "database-redis"
    build: ./database/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - database-postgres

  # Task Queue
  taskqueue-rabbitmq:
    container_name: "taskqueue-rabbitmq"
    build: ./taskqueue
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: "30s"
      timeout: "3s"
      retries: 3
    depends_on:
      - database-redis
    env_file:
      - ./scripts/local.env
