# Docker Compose Configuration for Rodan-lite
#    +-----+ Production version +-----+ 
# 
# ===========================================
# Summary of the system's services:
# - Frontend: rodan-client, nginx
# - Backend: rodan-main, iipsrv (for Diva.js)
# - Task Queue: rabbitmq
# - Database: postgres, redis (messaging websocket)
# - Workers: python3-celery, gpu-celery

volumes:
  rodan-resources:

services:
  # Frontend services
  frontend-nginx:
    container_name: "frontend-nginx"
    build: ./frontend/nginx
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      # VERSION: "nightly"
    ports:
      - "80:80"
      - "443:443"
      - "9002:9002"
    volumes:
      - "rodan-resources:/rodan/data"
    depends_on:
      - backend-iipsrv
      - backend-django
      - frontend-client

  frontend-client:
    container_name: "frontend-client"
    build: ./frontend/rodan-client
    volumes:
      - "./frontend/rodan-client/code:/code"
      - "./frontend/rodan-client/config/configuration.json:/client/configuration.json"

  # Backend service: web server for Django & IIP Server
  backend-django:
    container_name: "backend-django"
    build:
      context: .
      dockerfile: ./backend/rodan-main/Dockerfile
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      CELERY_JOB_QUEUE: None
    depends_on:
      - database-postgres
      - taskqueue-rabbitmq
      - database-redis
      - backend-iipsrv
    env_file:
      - ./scripts/local.env
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/rodan-main/code:/code/Rodan"

  backend-iipsrv:
    container_name: "backend-iipsrv"
    build: ./backend/iipsrv
    volumes:
      - "rodan-resources:/rodan/data"

  # Celery Controller: 
  # * celery-controller: The main controller for all-things celery
  celery-controller:
    container_name: "celery-controller"
    build:
      context: .
      dockerfile: ./backend/rodan-main/Dockerfile
    # command: bash -c "tail -f /dev/null"
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      CELERY_JOB_QUEUE: celery # THIS IS THE IMPORTANT PART
    depends_on:
      - backend-django
      - taskqueue-rabbitmq
      - database-postgres
      - database-redis
    env_file:
      - ./scripts/local.env
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/rodan-main/code:/code/Rodan"
  
  
  # Celery Workers: Python and GPU (and more!) 
  # * celery-python-workers
  # * celery-gpu-workers
  # * celery-...

  celery-python-workers:
    container_name: "worker-py3-celery"
    build:
      context: .
      dockerfile: ./workers/python3-celery/Dockerfile
    command: bash -c "tail -f /dev/null"
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      # CELERY_JOB_QUEUE: Python3
    env_file:
      - ./scripts/local.env
    depends_on:
      - backend-django
      - taskqueue-rabbitmq
      - database-postgres
      - database-redis
      - celery-controller
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/rodan-main/code:/code/Rodan"

  celery-gpu-workers:
    build:
      context: .
      dockerfile: ./workers/gpu-celery/Dockerfile
    command: bash -c "tail -f /dev/null"
    environment:
      TZ: America/Toronto
      SERVER_HOST: localhost
      # CELERY_JOB_QUEUE: GPU
    depends_on:
      - backend-django
      - taskqueue-rabbitmq
      - database-postgres
      - database-redis
      - celery-controller
    env_file:
      - ./scripts/local.env
    volumes:
      - "rodan-resources:/rodan/data"
      - "./backend/rodan-main/code:/code/Rodan"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
              # See more: 
              # - https://docs.docker.com/compose/how-tos/gpu-support/
              # - https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html

  # Database: PostgreSQL, Redit (messaging)
  database-postgres:
    container_name: "database-postgres"
    build: ./database/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./scripts/local.env

  database-redis:
    container_name: "database-redis"
    build: ./database/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - database-postgres

  # Task Queue
  taskqueue-rabbitmq:
    container_name: "taskqueue-rabbitmq"
    build: ./taskqueue
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: "30s"
      timeout: "3s"
      retries: 3
    depends_on:
      - database-redis
    env_file:
      - ./scripts/local.env
