#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

/run/setup
#sed -i "s/SERVER_HOST/${SERVER_HOST}/g" /etc/nginx/conf.d/ssl.conf

# Wait for everything to be up.
/run/wait-for-app backend-iipsrv:9003
/run/wait-for-app database-redis:6379
/run/wait-for-app backend-django:8000 --timeout=900
/run/wait-for-app frontend-client:80

nginx
#tail -f /var/log/nginx/access.log & tail -f /var/log/nginx/error.log
