#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

PIP=$(which pip3) || PIP=$(which pip)

cd /code/Rodan/code/jobs


cat << EOF | python3
new_backend = """{
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}"""
open("keras.json", "w").write(new_backend)
EOF

# Install Paco classifier
cd /
git clone -b v2.0.4 --depth 1 https://github.com/DDMAL/Paco_classifier.git
mv Paco_classifier .Paco_classifier
cd .Paco_classifier
which pip3 && $PIP install --no-cache-dir .

cd /code/Rodan/code
sed -i 's/#gpu //g' /code/Rodan/rodan/settings.py

# Temporary fix for OpenCV until https://github.com/DDMAL/Rodan/issues/639 is resolved.
pip install opencv-python==4.6.0.66
