name: CI - Backend components
run-name: "CI: Build Rodan-lite backend Docker images"
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/*backend*.yml'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  # ------- IIP Server -------
  backend-iipsrv-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build backend iipsrv
        run: docker compose backend-iipsrv
  # ------- Django -------
  backend-django-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build backend Django (rodan-main)
        run: docker compose backend-django
