name: CI - Backend components
run-name: "CI: Build Rodan-lite backend Docker images"
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      # ------- IIP Server -------
      - name: Build backend iipsrv
        run: docker compose build frontend-nginx
