name: CI - Database components
run-name: "CI: Build Rodan-lite database components"
on:
  push:
    branches:
      - develop
      - main
    paths:
      - "database/**"
      - '.github/workflows/*database*.yml'
  pull_request:
    paths:
      - "database/**"
  workflow_dispatch:

jobs:
  # ------- Postgres -------
  database-postgres-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build PostgreSQL Database
        run: docker compose build database-postgres
  # ------- Redis -------
  database-redis-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Build redis
        run: docker compose build database-redis
