name: CI - Workers components
run-name: "CI: Build Rodan-lite workers images"
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'workers/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'workers/**'
  workflow_dispatch:

jobs:
  workers-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      # ------- Python3 Celery -------
      - name: Build python3-celery workers
        run: docker compose build worker-py3-celery
      